version: '3.4'

services:

  volunteer:
    container_name: volunteer
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://volunteerdb:27017"
    depends_on:
      - volunteerdb
    ports:
      - "4000:80"

  organization:
    container_name: organization
    depends_on:
        - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrganizationConnectionString=Server=mssql;Database=OrganizationDb;User Id=sa;Password=Volunteerhub12345"
    ports:
      - "4001:80"

  ad:
    container_name: ad
    depends_on:
        - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:AdConnectionString=Server=mssql;Database=AdDb;User Id=sa;Password=Volunteerhub12345"
    ports:
      - "4002:80"

  volunteerhubbackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq
    ports:
      - "4003:80"

  identityserver:
    container_name: identityserver
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=Volunteerhub12345"
    ports:
      - "4004:80"

  notification:
    container_name: notification
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq
    ports:
      - "4005:80"

  mssql:
    container_name: organizationdb
    user: root
    environment:
      - SA_PASSWORD=Volunteerhub12345
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433" 
    volumes:
      - mssql_data:/var/opt/mssql
      - ./setup.sql:/usr/config/setup.sql

  volunteerdb:
    container_name: volunteerdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
    - "5672:5672"
    - "15672:15672"