version: '3.4'

services:
  volunteerdb:
    image: mongo

  volunteer:
    image: ${DOCKER_REGISTRY-}volunteer
    build:
      context: .
      dockerfile: Volunteer/Dockerfile

  organization:
    image: ${DOCKER_REGISTRY-}organization
    build:
      context: .
      dockerfile: Organization/Dockerfile

  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest

  volunteerhubbackend:
    image: ${DOCKER_REGISTRY-}volunteerhubbackend
    build:
      context: .
      dockerfile: VolunteerHubBackend/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile

  ad:
    image: ${DOCKER_REGISTRY-}ad
    build:
      context: .
      dockerfile: Ad/Dockerfile

  notification:
    image: ${DOCKER_REGISTRY-}notification
    build:
      context: .
      dockerfile: Notification/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine
    

volumes:
  mssql_data:
  mongo_data:


