version: '3.4'

services:
  volunteerdb:
    image: mongo

  volunteer:
    image: ${DOCKER_REGISTRY-}volunteer
    build:
      context: .
      dockerfile: Volunteer/Dockerfile

  organization:
    image: ${DOCKER_REGISTRY-}organization
    build:
      context: .
      dockerfile: Organization/Dockerfile

  organizationdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  volunteerhubbackend:
    image: ${DOCKER_REGISTRY-}volunteerhubbackend
    build:
      context: .
      dockerfile: VolunteerHubBackend/Dockerfile

volumes:
  organizationdb_data:
  mongo_data:

