version: '3.4'

services:
  volunteerdb:
    container_name: volunteerdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  volunteer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://volunteerdb:27017"
    depends_on:
      - volunteerdb
    ports:
      - "4000:80"

  organization:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4001:80"

