version: '3.4'

services:
  volunteerdb:
    image: mongo

  volunteer:
    image: ${DOCKER_REGISTRY-}volunteer
    build:
      context: .
      dockerfile: Volunteer/Dockerfile

  organization:
    image: ${DOCKER_REGISTRY-}organization
    build:
      context: .
      dockerfile: Organization/Dockerfile

volumes:
  mongo_data:

