export const CREATE_ORGANIZATION = "CREATE_ORGANIZATION";
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
export const GET_ORGANIZATION = "GET_ORGANIZATION";
export const GET_ORGANIZATION_LIST = "GET_ORGANIZATION_LIST";
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION";
