export const CREATE_VOLUNTEER = "CREATE_VOLUNTEER";
export const UPDATE_VOLUNTEER = "UPDATE_VOLUNTEER";
export const GET_VOLUNTEER = "GET_VOLUNTEER";
export const GET_VOLUNTEER_LIST = "GET_VOLUNTEER_LIST";
export const DELETE_VOLUNTEER = "DELETE_VOLUNTEER";
