name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
      
  volunteer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Volunteer
    - name: Build
      run: dotnet build Volunteer --no-restore
    - name: Test
      run: dotnet test Volunteer --no-build --verbosity normal
      
  organization:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Organization
    - name: Build
      run: dotnet build Organization --no-restore
    - name: Test
      run: dotnet test Organization --no-build --verbosity normal
